### ISSUE TITLE
请问如何运行?

### ISSUE THREAD

**Issue by zw963** [DreaminginCodeZH/pykeymacs#1]
我用的 Slackware 14.1, 使用 sudo pip 安装了一堆依赖, 不过仍然无法运行. 
(好吧, 我甚至不知道该运行那个 py 脚本, 以及工作的思路.)

我之前是使用 xbindkeys 加 xdotool 实现了 Linux 下的全局映射, 不过延迟的确有点高, 毕竟每一次快捷键操作, 都要执行好几个进程.

**Comment by zhanghai** [comment]
安装 python-evdev（python 3 版本，也可能名为 python3-evdev），然后使用 python 3 执行 pykeymacs.py（需要 root）。

**Comment by zw963** [comment]
仍然有错误. 

``` sh
Traceback (most recent call last):
  File "pykeymacs.py", line 1, in <module>
    from input import loop, select_device
  File "/home/zw963/Git/pykeymacs/input.py", line 4, in <module>
    from transform import on_event
  File "/home/zw963/Git/pykeymacs/transform.py", line 2, in <module>
    from key import Action, Combo, Key, Modifier
  File "/home/zw963/Git/pykeymacs/key.py", line 1, in <module>
    from enum import Enum, unique, IntEnum
ImportError: cannot import name unique
```

这个错误提示和之前一样的.

事实上, 我主要是通过包管理安装了 libevdev-1.2-x86_64, 通过 pip 安装了 evdev
`evdev                     - Bindings to the Linux input handling subsystem`,  我通过 pip search
没有发现 python-evdev 或 python3-evdev.

谢谢.

**Comment by zhanghai** [comment]
这个不是 evdev 的问题，大概是 python 3 不够新导致的。

你可以暂时通过将 key.py 中的 import unique 和 @unique 移除来 workaround。

**Comment by zw963** [comment]
还是有错,  `ImportError: cannot import name IntEnum`, 可能真是 Python3 版本的问题.
果然是术业有专攻, Python 我完全不懂, 我是搞 Ruby 的. 
Ruby 也有 libevdev 的包装, https://github.com/kui/revdev
不过我对 libevdev 缺少上下文, 如果你有时间, 
能否给一点点换绑任意快捷键的思路,  我根本不知道应该向那个设备发送
什么样的指令, 并且如何拦截并返回自定义的快捷键.

事实上, 如果在 README 中能简单介绍下几个 py 文件的用途, 
或者能否介绍一些针对性的文章, 特定讲换绑这一块, 我缺少这个上下文. 就万分感激了.

我想据此也写一个个人定制的 Ruby 版本, 彻底解决这个问题.

谢谢.

**Comment by zhanghai** [comment]
应该是 python 版本不够新的问题吧。我的 python：

``` bash
$ python --version
Python 3.4.3
```

原理和文件组织是相近的，由`input.py`利用`evdev`独占（grab）输入设备拦截所有输入，经`transform.py`转换，由`output.py`中的函数输出至`uinput`给下游。

**Comment by zw963** [comment]
解释的很清晰, 谢谢, 稍后有空我尝试改写下, 有问题再请教.

看到你的 python 版本输出, 我才发现我的 Python 版本默认是 2.
现在通过 python3 运行脚本, 提示 ImportError: No module named 'evdev'.
可能是因为通过 pip 安装的包都是 python2 的.

**Comment by zw963** [comment]
提示没有模块: `ImportError: No module named 'enum'`

尝试安装 enum, 又报错:

``` sh
$ sudo pip3.3 install enum
The directory '/home/zw963/.cache/pip/log' or its parent directory is not owned by the current user and the debug log has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
The directory '/home/zw963/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
The directory '/home/zw963/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
Collecting enum
  Downloading enum-0.4.4.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-a6vm86/enum/setup.py", line 25, in <module>
        main_module_doc = main_module.__doc__.decode('utf-8')
    AttributeError: 'str' object has no attribute 'decode'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/tmp/pip-build-a6vm86/enum/setup.py", line 25, in <module>

        main_module_doc = main_module.__doc__.decode('utf-8')

    AttributeError: 'str' object has no attribute 'decode'
```

**Comment by zw963** [comment]
符号链接改了下,

``` sh
$ python --version
Python 3.3.2
```

**Comment by zhanghai** [comment]
enum 似乎是 3.4 的？我现在不方便，你可以查下。

**Comment by zhanghai** [comment]
是的，enum 来自 3.4。

https://docs.python.org/3.4/library/enum.html

**Comment by zw963** [comment]
到这一步了. 汗~

``` sh
 ☠  $ sudo python ./pykeymacs.py
ID  Device               Name                                Phys
----------------------------------------------------------------------------------------
0   /dev/input/event0    Speakup                             speakup/input0
1   /dev/input/event1    AT Translated Set 2 keyboard        isa0060/serio0/input0
2   /dev/input/event2    Sleep Button                        PNP0C0E/button/input0
3   /dev/input/event3    Lid Switch                          PNP0C0D/button/input0
4   /dev/input/event4    Power Button                        LNXPWRBN/button/input0
5   /dev/input/event5    ST LIS3LV02DL Accelerometer         lis3lv02d/input0
6   /dev/input/event6    HP WMI hotkeys                      wmi/input0
7   /dev/input/event7    HDA Intel MID HDMI/DP,pcm=7         ALSA
8   /dev/input/event8    HDA Intel MID HDMI/DP,pcm=3         ALSA
9   /dev/input/event9    HDA Intel MID Dock Headphone        ALSA
10  /dev/input/event10   HDA Intel MID Headphone             ALSA
11  /dev/input/event11   HDA Intel MID Line                  ALSA
12  /dev/input/event12   HDA Intel MID Mic                   ALSA
13  /dev/input/event13   PS/2 Generic Mouse                  isa0060/serio1/input0
14  /dev/input/event14   HP Webcam [2 MP Macro]              usb-0000:00:1a.0-1.5/button
15  /dev/input/event15   SynPS/2 Synaptics TouchPad          isa0060/serio4/input0
16  /dev/input/event16   Video Bus                           LNXVIDEO/video/input0
17  /dev/input/event17   py-evdev-uinput                     

Select device [0-17]:
```

**Comment by zw963** [comment]
接下来如何操作?

**Comment by zhanghai** [comment]
选择 1，也就是你的键盘设备（AT Translated Set 2 keyboard）。

**Comment by zw963** [comment]
@DreaminginCodeZH , 求救， 在线等。

昨天我选择了最后一个， py-evdev-uinput, 今天早上开机， 进入 X 键盘就不再可以用了。
我切换回 single 模式， 重新设定 1， 貌似设不回来了？？

总之， 我现在只要一启动 X,  所有键盘失效， 甚至不能输入密码。

我该如何做？

**Comment by zw963** [comment]
昨天除了安装 Python3, pip 安装 evdev, 启动 sudo python ./pykeymacs.py, 没做其他什么事情。

**Comment by zw963** [comment]
在纯终端模式下， 启动电脑之后， 选择 1， 然后我不管输入什么按键， 都会被拦截， 在 Terminal 上显示按键输入， 这个时候我只能 <Ctrl+C> 退出， 然后重启后， 问题依旧。

**Comment by zhanghai** [comment]
请不要选择`python-evdev-uinput`：那个是程序自己创建的设备，用于将拦截的按键重新发送给系统处理。选择它可能会导致死循环。

Single 模式是什么？

这个设置不会被记住，所以应该不存在无法重新设定的问题。

重新启动 X 后键盘失效的问题很奇怪，因为这个程序所做不过是 Grab 你指定的设备，利用 uinput 创建用户空间输入设备重新发送输入。重新启动后程序如果没有被你设置成自启动，设备状态应当会复原的。

但如果一定无法输入，你暂时用屏幕键盘排除问题吧。

Terminal 上显示的不是按键输入，而是被转换后的按键输出，看到输出即是程序已经将这个按键序列发送给 uinput 模块。推测可能是你的 uinput 出了问题。

**Comment by zhanghai** [comment]
因为我在编写和使用过程中都没有遇到过问题，所以公开时没有程序会带来这些风险的考虑。

给你带来不便有些抱歉。

**Comment by zw963** [comment]
Single 模式是 Slackware 的维护模式， 事实上， 只要不启动 Ｘ 的模式， 都可以正常使用的。 但是只要启动 X 就无效了。

我看了下 Xorg 的日志， 有以下错误信息：

```
Failed to load module 'evdev' (module requirement mismatch)
No input driver matching 'evdev'
```

我想可能是我为了启动 python 脚本， 反复安装那几个 python 包当中的 evdev 所致?

**Comment by zw963** [comment]
我不知道该重装什么来解决这个问题。 实在不行只能完整的重装了， 有好多东西要重配。 汗~

我只有一个电脑， 没办法边查边试 （现在用的 Win7, 双系统), 而且我也缺少上下文。

你方便的话， 能否根据错误提示+发布版名称（Slackware)， 帮我查一下。 

谢谢了.

**Comment by zw963** [comment]
我觉得有极大的可能，其实跟我运行你的脚本没有关系。

无论如何， 知道有这个项目，我很兴奋呀，之前只是知道 Linux 存在这么个东西，
但是根本不确定能不能实现我想要的，现在我知道绝对可以的。

**Comment by zhanghai** [comment]
https://forums.gentoo.org/viewtopic-t-893088-start-0.html

似乎是 evdev 和 X 编译的版本不匹配，大概是你在尝试安装 evdev 相关的东西时错误安装了什么。

一个 Slackware 的结果

http://www.linuxquestions.org/questions/slackware-14/slackware-13-37-starts-but-my-mouse-and-keyboard-doesn't-work-4175415556/

你听说过 xf86-input-evdev 么？你是不是对它做了什么？

**Comment by zw963** [comment]
是的. 是我的错误造成的.

我昨天手贱, 

``` sh
xf86-input-evdev-2.9.0-x86_64-1 [inst=no]: xf86-input-evdev (Generic Linux input driver for the Xorg X server)
xf86-input-evdev-2.8.2-x86_64-1 [inst=yes]: xf86-input-evdev (Generic Linux input driver for the Xorg X server)
```

看到有新版本的 xf86-input-evdev, 我就装了, 结果就挂了, 我一直没想起来, 你说了下, 我又查了下 log,
发现漏了一行. 

``` sh
(EE) module ABI major version (6) doesn't match the server's version (7)
```

然后, 我从 ISO 中恢复 2.8.2, 现在可以用了.

万分感谢~

**Comment by zhanghai** [comment]
嗯，没事

**Comment by zw963** [comment]
Hi, @DreaminginCodeZH , 我尝试使用 Ruby 改写了 input.py, 有个小问题想请教一下, 方便的时候请解答.

https://github.com/zw963/rbkeymacs/blob/master/input.rb#L20

**Comment by zhanghai** [comment]
select 是等待 IO 完成，这个写法来自于 python-evdev 的 sample。我也没有细究过。

**Comment by zhanghai** [comment]
已过五天，将关闭此 issue。有问题欢迎另开 issue 询问。
