### ISSUE TITLE
使用过程中遇到的几个问题。Thanks.

### ISSUE THREAD

**Issue by zw963** [DreaminginCodeZH/pykeymacs#5]
1.  貌似无法和 .Xmodmap 无法一起工作。 
   我使用 .Xmodmap 脚本将 Capslock 更换到 R_ALT,  然后将 Capslock 设定为 L_CTRL
   这样，我使用右侧的 Alt 改大小写，使用 Capslock 作为 Ctrl.
   但是只要一启动 Python 脚本，.Xmodmap 就失效了, 怎么破? 
   总不至于把所有可能的组合都定义一遍吧？
2.  因为是全局设定快捷键，因此遇到了 Terminal 下和其他软件快捷键不一致的问题。
    请问类似的问题你是怎么解决的？ 例如: Meta+W 无法在 Terminal 复制高亮的文本。
    因为它绑定到了 Ctrl+C, 直接发送 break 信号了。 
    类似的问题在 Emacs 之中也存在，例如，你换绑了 Ctrl + / 到 Ctrl + Z,
    如果换回 Emacs， 按下 Ctrl + /,  直接调用 (suspend-frame) 了。
    如果可以针对特殊的进程，忽略 uinput 就好了。
3.  Alt+F, Alt+B 在 OpenSUSE 42.1 Gnome3 版下的 Firefox 地址栏中反应很迟钝，
    需要按好几下快捷键，才会动一下，而且， set-mark 命令（Ctrl+Space) 貌似
    工作也有问题， 设定 Mark 后，C-F, C-B 光标根本看不见动， 只有再次手动移动
    鼠标到地址栏， 才能恢复. 这样的问题在 LibreOffice 之中貌似不存在, 如果换做
    LinuxMint ，Firefox 也是正常的。
    我不知道是什么问题， 既然遇到了，就提出来供参考吧。

**Comment by zw963** [comment]
上面的第三个问题，我发现其实不是反应迟钝，而是得按两下，光标才会动一下。
貌似影响所有通过 Alt 设定的组合键。
如果 set mark, 根本就不会动。

我不确定这是 Gnome3 的问题还是代码的问题。

**Comment by zhanghai** [comment]
1. pykeymacs 为了绕开 X11 的局限工作在设备层上，Grab 输入设备后使用 uinput 发送变换过后的按键。看来 XModMap 没有对 uinput 生效。或许在开启 pykeymacs 后重新载入 XModMap 可以识别到 uinput 的设备。
2. 这个可以做，要结合 xdotool 那样的原理，获取 Windows class 之类。
3. 这个可能是不同的 Widget Toolkit 对无效的 KeyRelease 事件的处理导致的。目前 pykeymacs 出于简单只对 KeyPress 做了变换。

我只在被迫使用 WPS 这样的程序时暂时开启，所以不太遇到这些问题。

**Comment by zw963** [comment]
1.  第一个我按照你的方法试过，开启 pykeymacs 之后，重新运行 XmodMap,  按键变换回复了， 但是，
   pykeymacs 之中有关 Ctrl 的键绑定又无效了。 (Alt 的不影响)
2.  Python 不熟啊。虽然你的代码我基本上都读了，可是用什么库还是不知道， 可以给点提示吗？
3.  不清楚，但是 LinuxMint 17.3 Mate 就没事儿，现在是 openSUSE gnome 3, 有这个问题。

**Comment by zhanghai** [comment]
1. 我没有详细了解过，所以也不太清楚。可能和 XModMap 的工作原理和 KeyCode 有关。
2. Python XLib 可能可以。

**Comment by zw963** [comment]
谢谢针对  2  的建议， 1 请问你有什么建议？

是不是唯一的办法： 针对 Key 类里面的所有键，对于 Control + Key, Contrl + Alt + Key, Contrl + Shift + Key, Control + Alt + Shift + Key, 全部做个 transform ?

**Comment by zhanghai** [comment]
1 的原因应该是 pykeymacs 识别的是 XModMap 前的 Ctrl，然后 XModMap 再对 uinput 输出进行的变换。所以你可能要需要把 pykeymacs 代码中所有对 Ctrl 的变换改为对 Caps Lock 的变换，这样再由 XModMap 翻译为 Ctrl。

**Comment by zw963** [comment]
抱歉因为有事情, 这么晚才回复.

我按照你的字面意思来理解, 应该是:

原本:
`Combo(Modifier.CONTROL, Key.J): with_mark(Key.LEFT)`
改为
`Combo(Key.CAPSLOCK, Key.J): with_mark(Key.LEFT)`

但是出错了,

``` sh
Traceback (most recent call last):
  File "pykeymacs.py", line 1, in <module>
    from input import loop, select_device
  File "/home/zw963/Git/pykeymacs/input.py", line 4, in <module>
    from transform import on_event
  File "/home/zw963/Git/pykeymacs/transform.py", line 60, in <module>
    Combo(Key.CAPSLOCK, Key.J): with_mark(Key.LEFT),
  File "/home/zw963/Git/pykeymacs/key.py", line 319, in __init__
    raise ValueError("modifiers should be a set")
ValueError: modifiers should be a set
```

**Comment by zw963** [comment]
当我在 pykeymacs 之后, 再次运行 xmodmap 时, 变换其实是生效的.

例如, 当我在 Terminal 下按下 Capslock + C 时, Terminal 是可以检测到 INT 信号的.

只是在 pykeymacs 中定义的那些个快捷键失效.

**Comment by zhanghai** [comment]
是的，因为 xmodmap 工作在 pykeymacs 之后，pykeymacs 见到的还是 CapsLock，经过 xmodmap 才被翻译为 Ctrl。所以 pykeymacs 当然不会做变换。

所以想要解决只有两种办法：
1. 在 pykeymacs 中把对 Ctrl 的变换改写为对 CapsLock 的变换。或许你可以改一下代码，在 Transform 前 hard code 这个变换。
2. 停止使用 xmodmap，转而寻求在 evdev 这一层之前完成对 CapsLock 的变换。一个可能的方式是 Hack X 的键盘布局配置。详情我也没有很了解。

**Comment by zw963** [comment]
谢谢, 我首先尝试了下修改代码, 但是似乎不像我期望的方式那样工作. 

下面是 diff:

https://github.com/DreaminginCodeZH/pykeymacs/compare/master...zw963:master

请指导下, 是不是什么地方搞错了.
对于 Python 和 uinput 都不熟 ....

**Comment by zhanghai** [comment]
看起来你为 Caps Lock 建立了一个模式，这样的话应该是你先按下 CapsLock，再按下 J，会导致 Left 被按下。

**Comment by zw963** [comment]
> 看起来你为 Caps Lock 建立了一个模式

是的, 我是创建了一个模式, 只是照葫芦画瓢, 并不真正了解工作机理, 之所以这样做,是因为: `Combo(Key.CAPSLOCK, Key.J): with_mark(Key.LEFT)` 中, `Key.CAPSLOCK` 直接作为修饰键是出错的.

> 这样的话应该是你先按下 CapsLock，再按下 J，会导致 Left 被按下。
> 并不是这样的, CAPSLOCK 还是之前的行为(像个开关), 而不是像普通修饰键那样按下不放才有效.
> 举例说明: 按下 CAPSLOCK 同时按 J 并没有生效, 只有按下后立即放开, 再按 J 才会生效.

你帮我看下这个方案是否还有可行性, 实在没有的话,  我只能 Google 尝试找一个 xmodmap 替代方案了.

**Comment by zhanghai** [comment]
我的意思是在 `on_event` 中调用 `on_key` 时检查到 CapsLock 则提前转为 Ctrl，你可以试一试。

另一种方式指的是把 X 认为的 KeySym 和 KeyCode 的映射里强行把 CapsLock 认为是 Ctrl。

**Comment by zw963** [comment]
> 我的意思是在 on_event 中调用 on_key 时检查到 CapsLock 则提前转为 Ctrl，你可以试一试。

谢谢, 根据你的建议, 问题已经解决, 仅仅加了两行代码, 现在连 xmodmap 都可以扔掉了.

``` py
def on_key(key, action):
    if key == Key.CAPSLOCK:
        key = Key.LEFT_CTRL

    if key in Modifier.get_all_keys():
        update_pressed_modifier_keys(key, action)
        send_key_action(key, action)
    elif not action.is_pressed():
        send_key_action(key, action)
    else:
        transform_key(key, action)
```

现有的映射代码也不需要做任何改动, 之前把问题想的太复杂了.

**Comment by zw963** [comment]
现在遇到的主要问题, 就剩下在 openSUSE 下,  很多软件 Alt + Hotkey 工作不正常.

之前认为快捷键需要按好几下才动一下, 现在用了一阵子, 发现了其中的规律.
其实问题就是, 每一个 Alt + Hotkey 操作, 都需要按两下, 第二下才会生效.

**Comment by zw963** [comment]
下面的输出是我在 'aaa bbb ccc ddd eee' 这个字符串中间单词 ddd 前后位置来回按的输出, 

基本上, 就是按下 `Alt + J (word_left)` 跳到 ddd 前面, `Alt + L (word_right)` 跳到 ddd 后面.
反复重复了几次的 log  输出.

根据观察, 来回移动时, 有时候只按一次也可以跳过去.

我很奇怪, 下面的 RIGHT_CTRL 是如何激发的. 我发誓我没有碰到它. 
我唯一做的事情只是光标从 DDD 后面开始, Alt + J, Alt + L Alt + J Alt + L Alt + J Alt + L, 重复了三次而已.
[PRE] LEFT_ALT
[REP] LEFT_ALT
[REP] LEFT_ALT
[REP] LEFT_ALT
[REP] LEFT_ALT
[REL] LEFT_ALT
[PRE] RIGHT_CTRL
[PRE] LEFT
[REL] LEFT
[REL] RIGHT_CTRL
[PRE] LEFT_ALT
[REL] J
[REL] LEFT_ALT
[PRE] RIGHT_CTRL
[PRE] LEFT
[REL] LEFT
[REL] RIGHT_CTRL
[PRE] LEFT_ALT
[REL] J
[REL] LEFT_ALT
[PRE] RIGHT_CTRL
[PRE] RIGHT
[REL] RIGHT
[REL] RIGHT_CTRL
[PRE] LEFT_ALT
[REL] L
[REL] LEFT_ALT
[PRE] RIGHT_CTRL
[PRE] RIGHT
[REL] RIGHT
[REL] RIGHT_CTRL
[PRE] LEFT_ALT
[REL] L
[REL] LEFT_ALT
[PRE] RIGHT_CTRL
[PRE] LEFT
[REL] LEFT
[REL] RIGHT_CTRL
[PRE] LEFT_ALT
[REL] J
[REL] LEFT_ALT
[PRE] RIGHT_CTRL
[PRE] LEFT
[REL] LEFT
[REL] RIGHT_CTRL
[PRE] LEFT_ALT
[REL] J
[REL] LEFT_ALT
[PRE] RIGHT_CTRL
[PRE] RIGHT
[REL] RIGHT
[REL] RIGHT_CTRL
[PRE] LEFT_ALT
[REL] L
[REL] LEFT_ALT
[PRE] RIGHT_CTRL
[PRE] RIGHT
[REL] RIGHT
[REL] RIGHT_CTRL
[PRE] LEFT_ALT
[REL] L
[REL] LEFT_ALT
[PRE] RIGHT_CTRL
[PRE] LEFT
[REL] LEFT
[REL] RIGHT_CTRL
[PRE] LEFT_ALT
[REL] J
[REL] LEFT_ALT
[PRE] RIGHT_CTRL
[PRE] LEFT
[REL] LEFT
[REL] RIGHT_CTRL
[PRE] LEFT_ALT
[REL] J
[REL] LEFT_ALT
[PRE] RIGHT_CTRL
[PRE] RIGHT
[REL] RIGHT
[REL] RIGHT_CTRL
[PRE] LEFT_ALT
[REL] L
[REL] LEFT_ALT
[PRE] RIGHT_CTRL
[PRE] RIGHT
[REL] RIGHT
[REL] RIGHT_CTRL
[PRE] LEFT_ALT
[REL] L
[REL] LEFT_ALT

**Comment by zw963** [comment]
下面的是 uniq 之后的结果: (去除了连续的重复)

[PRE] LEFT_ALT
[REP] LEFT_ALT
[REL] LEFT_ALT
[PRE] RIGHT_CTRL
[PRE] LEFT
[REL] LEFT
[REL] RIGHT_CTRL
[PRE] LEFT_ALT
[REL] J
[REL] LEFT_ALT
[PRE] RIGHT_CTRL
[PRE] LEFT
[REL] LEFT
[REL] RIGHT_CTRL
[PRE] LEFT_ALT
[REL] J
[REL] LEFT_ALT
[PRE] RIGHT_CTRL
[PRE] RIGHT
[REL] RIGHT
[REL] RIGHT_CTRL
[PRE] LEFT_ALT
[REL] L
[REL] LEFT_ALT
[PRE] RIGHT_CTRL
[PRE] RIGHT
[REL] RIGHT
[REL] RIGHT_CTRL
[PRE] LEFT_ALT
[REL] L
[REL] LEFT_ALT
[PRE] RIGHT_CTRL
[PRE] LEFT
[REL] LEFT
[REL] RIGHT_CTRL
[PRE] LEFT_ALT
[REL] J
[REL] LEFT_ALT
[PRE] RIGHT_CTRL
[PRE] LEFT
[REL] LEFT
[REL] RIGHT_CTRL
[PRE] LEFT_ALT
[REL] J
[REL] LEFT_ALT
[PRE] RIGHT_CTRL
[PRE] RIGHT
[REL] RIGHT
[REL] RIGHT_CTRL
[PRE] LEFT_ALT
[REL] L
[REL] LEFT_ALT
[PRE] RIGHT_CTRL
[PRE] RIGHT
[REL] RIGHT
[REL] RIGHT_CTRL
[PRE] LEFT_ALT
[REL] L
[REL] LEFT_ALT
[PRE] RIGHT_CTRL
[PRE] LEFT
[REL] LEFT
[REL] RIGHT_CTRL
[PRE] LEFT_ALT
[REL] J
[REL] LEFT_ALT
[PRE] RIGHT_CTRL
[PRE] LEFT
[REL] LEFT
[REL] RIGHT_CTRL
[PRE] LEFT_ALT
[REL] J
[REL] LEFT_ALT
[PRE] RIGHT_CTRL
[PRE] RIGHT
[REL] RIGHT
[REL] RIGHT_CTRL
[PRE] LEFT_ALT
[REL] L
[REL] LEFT_ALT
[PRE] RIGHT_CTRL
[PRE] RIGHT
[REL] RIGHT
[REL] RIGHT_CTRL
[PRE] LEFT_ALT
[REL] L
[REL] LEFT_ALT

**Comment by zhanghai** [comment]
这个我就不知道了……

**Comment by zw963** [comment]
那个太长了, 不好意思, 这个也许对问题有点帮助.

我执行的快捷键是下面的这个.

``` el
Combo(Modifier.ALT, Key.W): [Combo({Modifier.CONTROL, Modifier.SHIFT}, Key.C), set_mark(False)],
```

下面的记录是, 我在 Emacs 下面, 首先选择了一个选区, 然后按下 M-w 的日志.
我我贴的日志里面只有 M-w 这个操作, 第一次是无效的, 第二次才有效.
因此我贴了两个记录, 第一次记录是第一次按下的. 第二个记录是第二次按下的.
第一次内容没有被复制, mark 也没有清除, 第二次才是真正的操作.

贴出来才发现, 两者其实是一样的. 只有第一次有效.

``` sh
[PRE] LEFT_SHIFT
[PRE] RIGHT_CTRL
[PRE] C
[REL] C
[REL] RIGHT_CTRL
[REL] LEFT_SHIFT
[PRE] LEFT_ALT
[REL] W
[REL] LEFT_ALT
```

``` sh
[PRE] LEFT_SHIFT
[PRE] RIGHT_CTRL
[PRE] C
[REL] C
[REL] RIGHT_CTRL
[REL] LEFT_SHIFT
[PRE] LEFT_ALT
[REL] W
[REL] LEFT_ALT
```

**Comment by zw963** [comment]
嘿，非常感谢你的热心帮助。

最终，我在 github 找到了一个非常匹配我的需求的项目:
https://github.com/kui/rbindkeys
使用我非常熟悉的语言 Ruby 编写，而且也支持不同的 process 不同的快捷键绑定。
我做了一些 hack, 我甚至针对 同样是 Terminal 下是否开启 nano, 做了不同的绑定。
已经用了三天了，目前表现完美。

虽然表现出来的行为不完全一致，但是 Firefox 仍然存在问题。
貌似这就不应该是 redev 的问题了，因为 Chrome 完全没问题。

既然极大的可能不是包的问题，这个问题我就先关了。

Thanks.
